### ISSUE TITLE
Using Timer instead of "Loop with wait"

### ISSUE THREAD

**Issue by ijnek** [bit-bots/humanoid_base_footprint#24]
Rather than having a loop with a "wait" inside, it would seem better to have a timer that fires at a set frequency, and do everything inside the timer callback.

**Comment by Flova** [comment]
Depending on the settings of the executor we would need to take care that the timer callbacks happen sequentially (under load or if a tf hangs in a time out or something similar). If it is set to be strictly sequentially we would need to take care that the message callbacks and maybe have a look at the way the callbacks are queued. Afaik timers always come first (before subscribers). This could be an issue if the robot has a high load and the timer callback doesn't finish until the next one comes. This would result in the callback having outdated data.

**Comment by SammyRamone** [comment]
We used rate.sleep() before, but this is broken in ROS2 when you want to use it in simulation https://github.com/ros2/rclcpp/issues/465

**Comment by ijnek** [comment]
Sorry for the delayed reply!
@SammyRamone When did you try using rate.sleep()? I see in https://github.com/ros2/rclcpp/issues/1730, they've made some improvements (and this was only merged 3 months ago).

**Comment by ijnek** [comment]
> Depending on the settings of the executor we would need to take care that the timer callbacks happen sequentially (under load or if a tf hangs in a time out or something similar). If it is set to be strictly sequentially we would need to take care that the message callbacks and maybe have a look at the way the callbacks are queued. Afaik timers always come first (before subscribers). This could be an issue if the robot has a high load and the timer callback doesn't finish until the next one comes. This would result in the callback having outdated data.

If we use a MutuallyExclusive callbackgroup with a timer (using `create_wall_timer`), as described in [Callback groups(ROS2 Tutorials)](https://docs.ros.org/en/galactic/Concepts/About-Executors.html#callback-groups), I don't think this would be an issue.

---

Edit:

MutuallyExclusive is the default callback group used for a node. Read comment below.

**Comment by ijnek** [comment]
> Depending on the settings of the executor we would need to take care that the timer callbacks happen sequentially (under load or if a tf hangs in a time out or something similar). If it is set to be strictly sequentially we would need to take care that the message callbacks and maybe have a look at the way the callbacks are queued. Afaik timers always come first (before subscribers). This could be an issue if the robot has a high load and the timer callback doesn't finish until the next one comes. This would result in the callback having outdated data.

So, I've played around with different executors, and callback groups in an isolated environment, and I conclude that some strange "hogging" issues *could* happen if callbacks take too long.

I think the conceptual issue is however, that if callbacks were allowed to take long, such issues would arise everywhere in ros codebases. We should keep callbacks as short as possible.

In regards to this node, the loop runs at a fairly low frequency (30fps). The callback has to take as long as 33ms, which seems like a very long time for a callback routine.

> tf hangs in a time out

I don't have too much knowledge on this, but can we keep the default lookupTransform timeout at 0 (the default parameter)? That way, `lookupTransform` should never hang. If `lookupTransform` fails, then we can simply not publish the transform the base_footprint.

**Comment by Flova** [comment]
But if these issues arise if the callbacks are used, why not use a loop instead of callbacks in this case. Are there any downsides to it? It should not happen that the real-time constraint is not met, but we are not using a real rt os so it could be the case and the damage should be minimal. A lower publishing frequency would be only a minor degradation of the system, and it would naturally arise if a loop is used.

Regarding the tf, dropping the step if tf data is not ready is an option, but if there is some minor delay that results in tf arriving a few ms late this would result in no tf data being published at all instead of publishing the base footprint for this time step a bit late.

**Comment by ijnek** [comment]
> Are there any downsides to it? 

Not that I can immediately think of... The reason I brought this up was because in  [roscpp/Writing a Simple Publisher and Subscriber (C++)](http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28c%2B%2B%29) they use a loop with a sleep, while in the newer [ros2/Writing a simple publisher and subscriber (C++)](https://docs.ros.org/en/foxy/Tutorials/Writing-A-Simple-Cpp-Publisher-And-Subscriber.html) they use timers. This hinted (implicitly) to me that timers were the recommended way of doing things for ros2.

I'd like to put aside the Timer against "Loop with wait", and continue a discussion about publishing transforms as they become available. As it diverges from the title of this issue, I've opened another issue: https://github.com/ros-sports/humanoid_base_footprint/issues/32

**Comment by ijnek** [comment]
As https://github.com/ros-sports/humanoid_base_footprint/issues/32 was closed without a solution, I'd like to discuss this issue a bit more.

In regards to this piece of code below taken from [base_footprint.cpp#L86](https://github.com/ros-sports/humanoid_base_footprint/blob/c8d0e3acaabfb25b17e8f4af48e4ac72aa7ae91c/src/base_footprint.cpp#L86):

```
      tf_right = tfBuffer_
        ->lookupTransform(
        base_link_frame_,
        r_sole_frame_,
        this->now(),
        rclcpp::Duration::from_nanoseconds(1e9 * 0.1));
      tf_left = tfBuffer_
        ->lookupTransform(
        base_link_frame_,
        l_sole_frame_,
        this->now(),
        rclcpp::Duration::from_nanoseconds(1e9 * 0.1));
      odom = tfBuffer_
        ->lookupTransform(
        base_link_frame_, odom_frame_,
        this->now(), rclcpp::Duration::from_nanoseconds(1e9 * 0.1));
```

what's the problem with:

* using tf2::TimePointZero, with zero timeout - always getting the latest transform seems to make sense
* Calling `now()` once and storing timestamp. I'd expect repeatedly calling `now()` as it currently is would collect tfs at different times (and make lookupTransform block for longer)
    ```
      auto stamp = now();
      f_right = tfBuffer_
            ->lookupTransform(
            base_link_frame_,
            r_sole_frame_,
            stamp,
            rclcpp::Duration::from_nanoseconds(1e9 * 0.1));
          tf_left = tfBuffer_
            ->lookupTransform(
            base_link_frame_,
            l_sole_frame_,
            stamp,
            rclcpp::Duration::from_nanoseconds(1e9 * 0.1));
          odom = tfBuffer_
            ->lookupTransform(
            base_link_frame_, odom_frame_,
            stamp, rclcpp::Duration::from_nanoseconds(1e9 * 0.1));
      ```

Having humanoid_base_footprint publish at a reliable high rate would be important so other nodes don't have to wait long and getting the transform.

**Comment by Flova** [comment]
At first glance, I see no issue with using the newest transform. The problem is that there is not only one transform. There are multiple ones. Getting the newest from all of them would lead to errors, as different parts of the robot state are effectively queried at different points in time. We could discuss how significant these errors are, but another open point would also be how the timestamp of the published base_footprint is determined if multiple points in time are used to "approximate" it. This method would lead to a reliable frequency with a lower accuracy, being beneficial for things that need a low reaction time,

Calling now once seems like a good way of handling this, as all transforms are taken from the same time stamp. This needs a longer timeout because there is no way, that the transform lookup is ready instantly in the next line. This comes at the cost of wasting much time waiting for the transforms to arrive for the "now" time, effectively reducing the maximum possible frequency of the publisher. The transforms that are published would be as recent as possible, but the overall rate would be lower. This method would lead to a lower frequency with an exact accuracy, being beneficial for less time critical transformations that require a high accuracy like the ipm.

The ideal case would be to somehow wait until a common timestamp for all required transforms is available (timestap could be <now), publish the footprint and repeat. In this case no time is wasted by waiting for the arrival of the full robot state at the time when the loop is started. Instead, the newest complete robot state is used, even if it is a bit older than the beginning of the loop. We obviously wait for a small timeout if our rate exceeds the rates of the previous transforms, but this should not be an issue. This implementation would add a bit of complexity, but should be doable and it combines the strength of both proposed approaches by not waiting for the timestamp from when the loop starts and also not being inaccurate.

**Comment by Flova** [comment]
Just a quick example, no guarantees regarding correctness

```c++
odom = tfBuffer_->lookupTransform(
      base_link_frame_, odom_frame_,
      tf2::TimePointZero, 
      rclcpp::Duration::from_nanoseconds(0));
f_right = tfBuffer_->lookupTransform(
      base_link_frame_,
      r_sole_frame_,
      odom.stamp,
      rclcpp::Duration::from_nanoseconds(1e9 * 0.2));
tf_left = tfBuffer_->lookupTransform(
        base_link_frame_,
        l_sole_frame_,
        odom.stamp,
        rclcpp::Duration::from_nanoseconds(1e9 * 0.2));
```

This selects the newest transform it can get for one chain and waits until the rest of them becomes available for the timestamp of the newest first one. The order in which this is checked should not matter, as they all need to be available.

**Comment by ijnek** [comment]
You summarised the issue pretty well. 

> The ideal case would be to somehow wait until a common timestamp for all required transforms is available (timestap could be <now), publish the footprint and repeat. In this case no time is wasted by waiting for the arrival of the full robot state at the time when the loop is started. Instead, the newest complete robot state is used, even if it is a bit older than the beginning of the loop. We obviously wait for a small timeout if our rate exceeds the rates of the previous transforms, but this should not be an issue. This implementation would add a bit of complexity, but should be doable and it combines the strength of both proposed approaches by not waiting for the timestamp from when the loop starts and also not being inaccurate.

What about the following implementation? We'd have a loop that runs at a certain frequency (like 20Hz or so). In the loop, we find the most recent common transform time using the following, and get the transforms at that point in time using the following:

```
    // Find a common time stamp by taking the minimum
    auto stamp = std::min(
      {
        rclcpp::Time{tfBuffer_->lookupTransform(base_link_frame_, r_sole_frame_, tf2::TimePointZero).header.stamp},
        rclcpp::Time{tfBuffer_->lookupTransform(base_link_frame_, l_sole_frame_, tf2::TimePointZero).header.stamp},
        rclcpp::Time{tfBuffer_->lookupTransform(base_link_frame_, odom_frame_, tf2::TimePointZero).header.stamp}
      });

    // Lookup transforms with the common timestamp
    tf_right = tfBuffer_->lookupTransform(base_link_frame_, r_sole_frame_, stamp);
    tf_left = tfBuffer_->lookupTransform(base_link_frame_, l_sole_frame_, stamp);
    odom = tfBuffer_->lookupTransform(base_link_frame_, odom_frame_, stamp);
```

I don't like the above as it calls lookupTransform (which I don't know how efficient the call is) multiple times, so ideally, we would want something like:

```
    // Find a common time stamp
    auto stamp = tfBuffer_->getLatestCommonTimestamp({base_link_frame, r_sole_frame_, l_sole_frame_, odom_frame_});

    // Lookup transforms with the common timestamp
    tf_right = tfBuffer_->lookupTransform(base_link_frame_, r_sole_frame_, stamp);
    tf_left = tfBuffer_->lookupTransform(base_link_frame_, l_sole_frame_, stamp);
    odom = tfBuffer_->lookupTransform(base_link_frame_, odom_frame_, stamp);
```

The issue is tf2 doesn' seem to provide a nice way of finding a common timestamp for more than a pair of frames.
Should we suggest adding the ``getLatestCommonTimestamp({frame_1, frame_2, frame_3, ...})`` method to tf2?

**Comment by Flova** [comment]
I like the implementation you proposed! 
I have nothing to add to it. 

After a quick look into the implementation of LookupTransform it seems like it does a recursive call on one of its two subcomponents which determines if a transform is available. This is done until the timeout is reached. I would guess that the forward kinematics part is not too expensive ether for reasonably sized trees. We could call the subcomponent that determines if this part of the tree is available manually, but it just returns a boolean, so we still need to call the forward kinematics part to get the timestamp. While it is a bit wastfull to calculate the forward kinematics once to just get the stamp it is the easiest solution and the whole process should be quite fast nevertheless.
