### ISSUE TITLE
Remove .rdmanifest

### ISSUE THREAD

**Issue by ijnek** [bit-bots/humanoid_base_footprint#25]
I'd like to remove `.rdrmanifest` as it is specific to bit-bots.

Refer to this [conversation on a PR](https://github.com/ros-sports/humanoid_base_footprint/pull/22#discussion_r820321874)

**Comment by lilioid** [comment]
It's not entirely a Bit-Bots specific thing but a rosdep thing.
[REP 112](https://ros.org/reps/rep-0112.html#rdmanifest-syntax) defines the rdmanifest. It is generally used to teach rosdep how to do source installations (instead of pip or apt). This means that the rdmanifest could safely be removed once proper apt releases are done and the package is properly recognized by rosdep using these apt releases.

Before that, one could, for example, teach rosdep how to install the package by creating a rosdep definition file for it (similar to files in `/etc/apt/sources.list.d/`. We do so in [a file in bitbots_tools](https://github.com/bit-bots/bitbots_tools/blob/master/rosdep_source.yml) which is then used by our CI to install dependencies from source.

I hope this explanation makes sense, hit me up if there are more questions :)

**Comment by ijnek** [comment]
@ftsell Thanks for your input! I was unaware that .rdmanifest was defined in a REP.

I found it strange that I'd never come across it doing ROS2. A [response on ROS Answers](https://answers.ros.org/question/255238/what-is-the-status-of-rdmanifests/?answer=255254#post-id-255254) suggests why I don't see them being used often.

So, we'll proceed with removing `.rdmanifest`, and someone should remove the `humanoid_base_footprint` entry from [bitbots_tools/rosdep_source.yaml](https://github.com/bit-bots/bitbots_tools/blob/ee71ff2fc56fac4387c309c0530717277fda92de/rosdep_source.yml#L199).

Shoud be straight forward tell me if I'm missing something.

**Comment by lilioid** [comment]
I understand wanting to clean up the repository, but would prefer to defer the removal until we have set up proper releases and rosdep definitions.
Otherwise, yes, once we decide to remove it a simple deletion of the file is all there is to it.

The main reason for this is that we need a way to install packages from only a dependency name in our CI, and that definition file in `bitbots_tools` in combination with `.rdmanifest` is how we implemented that.

**Comment by ijnek** [comment]
Repos maintained on ros-sports targets the general audience, and if bit-bots requires a specific file to exist in the repo, then making a fork with a patch (and continuously performing a "fetch and merge" from upstream) would probably be the way to go.

Although the release date of this package is up to @ros-sports/humanoid_base_footprint maintainers, ideally CI infrastructure should be able to deal with unreleased repositories that don't contain a `.rdmanifest`. Otherwise, this issue will arise everytime bit-bots tries to work on an unreleased package not maintained by bit-bots.

For example, how do you deal with using [ros-sports/soccer_interfaces](https://github.com/ros-sports/soccer_interfaces)?

**Comment by ijnek** [comment]
Could you use the vcs command, as described in https://github.com/ros-sports/humanoid_base_footprint#installation to build the unreleased depencies? This method is also used in [Tutotiral - Source installation of ROS2](https://docs.ros.org/en/foxy/Installation/Ubuntu-Development-Setup.html#get-ros-2-code)

**Comment by ijnek** [comment]
@ros-sports/humanoid_base_footprint I'd like some actionables for this issue. Is there a way for bit-bots to get around the removal of `.rdmanifest`, such as the ones Ive suggested?

**Comment by SammyRamone** [comment]
I don't really have knowledge about this. I think @ftsell or @timonegk need to answer this

**Comment by lilioid** [comment]
> Could you use the vcs command, as described in https://github.com/ros-sports/humanoid_base_footprint#installation to build the unreleased depencies? This method is also used in [Tutotiral - Source installation of ROS2](https://docs.ros.org/en/foxy/Installation/Ubuntu-Development-Setup.html#get-ros-2-code)

The thing is that it needs to be a machine-readable specification, and the method in which the repo is cloned is not what it's about.

If you want to have the file removed, though, I think we should be able to host it in our bitbots_tools repository alongside the previously mentioned custom rosdep definitions.
That way you can get rid of the customized bit-bots way of doing things (the .rdmanifest **does** specify a custom bit-bots way of installing things after all) and things should keep working in our CI.
