### ISSUE TITLE
Missing call to loop()

### ISSUE THREAD

**Issue by ijnek** [bit-bots/humanoid_base_footprint#30]
[BaseFootprintBroadcaster::loop()](https://github.com/ros-sports/humanoid_base_footprint/blob/8344154b2f877d27f57d153b7a3c20dcf816e3c9/src/base_footprint.cpp#L66) is never called. Where do we start loopin' ?

**Comment by SammyRamone** [comment]
Yes this is true, the loop is currently not called and therefore the node does not work. This was done due to the change in https://github.com/ros-sports/humanoid_base_footprint/commit/d2a482fab0705849213f332e335445a4d28f1e41 where the node was changed to be a component. The main() was removed which called the loop before.
Actually, I don't know how the correct procedure is with component nodes as I have never used them before. There seem to be multiple methods on how to use them https://docs.ros.org/en/rolling/Concepts/About-Composition.html#using-components
All of them look a bit like additional overhead, but maybe I am missing something?

**Comment by ijnek** [comment]
Oops, that'll be a bug introduced by me. 

The documentation on compositions are somewhat lacking. The idea is to have many ways for a node to be used. To note, [line 41 from CMakeLists.txt](https://github.com/ros-sports/humanoid_base_footprint/blob/8344154b2f877d27f57d153b7a3c20dcf816e3c9/CMakeLists.txt#L41) creates an executable called base_footprint, along with the rclcpp component, which means you can just call `ros2 run humanoid_base_footprint base_footprint`. This means you can run the node as a normal executable like you use to, with no overhead (although I don't know what overhead exists in terms of performance when using compoents).

Relying on calling the `loop` method seems unnatural for a ROS2 node (and hence completely flew over me), and will catch out others trying to use base_footprint as a library.

It seems however, the issue of loop not getting called, will be resolved by the changes proposed in https://github.com/ros-sports/humanoid_base_footprint/issues/32 anyway.

**Comment by ijnek** [comment]
This [Japanese blog post](https://qiita.com/NeK/items/775c0ddb4e10ed091068) covers reasons for using components fairly well, you just have to translate it to English using google chrome's translation.

**Comment by SammyRamone** [comment]
Thanks for the clarification, the documentation is indeed lacking a bit on this topic.
I agree, that this issue will be resolved by #32 so I guess we don't need to take additional actions for now.

**Comment by ijnek** [comment]
As #32 was closed without a solution, I am going to investigate fixing this bug.
